version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_app_development
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: todo-backend
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      RAILS_ENV: development
      JWT_SECRET_KEY: your-secret-key
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db-data:
